// png
export { default as IconApp } from '@/assets/images/pln-with-text.png'
// Svg with Vue component
export { default as IconLightningSlash } from '@/components/icons/IconLightningSlash.vue'
export { default as IconSmileySad } from '@/components/icons/IconSmileySad.vue'
export { default as IconMonitor } from '@/components/icons/IconMonitor.vue'
export { default as IconSwap } from '@/components/icons/IconSwap.vue'
export { default as IconDotOutline } from '@/components/icons/IconDotOutline.vue'
export { default as IconPlugs } from '@/components/icons/IconPlugs.vue'
export { default as IconGauge } from '@/components/icons/IconGauge.vue'
export { default as IconBox } from '@/components/icons/IconBox.vue'
export { default as IconFileSearch } from '@/components/icons/IconFileSearch.vue'
export { default as IconWallet } from '@/components/icons/IconWallet.vue'
export { default as IconBars3 } from '@/components/icons/IconBars3.vue'
export { default as IconFilter } from '@/components/icons/IconFilter.vue'
export { default as IconFileX } from '@/components/icons/IconFileX.vue'
export { default as IconNetworkDisconnected } from '@/components/icons/IconNetworkDisconnected.vue'
export { default as IconNetworkChange } from '@/components/icons/IconNetworkChange.vue'
export { default as IconLinkBreak } from '@/components/icons/IconLinkBreak.vue'
export { default as IconLockKey } from '@/components/icons/IconLockKey.vue'
export { default as IconDatabase } from '@/components/icons/IconDatabase.vue'
export { default as IconPolygon } from '@/components/icons/IconPolygon.vue'
export { default as IconToolbox } from '@/components/icons/IconToolbox.vue'
export { default as IconVector1 } from '@/components/icons/IconVector-1.vue'
export { default as IconVector } from '@/components/icons/IconVector.vue'

//svg
export { default as IconRedThunder } from '@/assets/icons/red-thunder.svg'
export { default as IconWhiteMaintenance } from '@/assets/icons/white-maintenance.svg'
export { default as IconSmileySadRed } from '@/assets/icons/smiley-sad-red.svg'
export { default as IconEllipseBlack } from '@/assets/icons/ellipse-black.svg'
export { default as IconEllipseGreen } from '@/assets/icons/ellipse-green.svg'
export { default as IconEllipseRed } from '@/assets/icons/ellipse-red.svg'
export { default as IconEllipseYellow } from '@/assets/icons/ellipse-yellow.svg'
export { default as IconSmileyAngry } from '@/assets/icons/smiley-angry.svg'
export { default as IconUsersThree } from '@/assets/icons/users-three.svg'
export { default as IconWarningDiamond } from '@/assets/icons/warning-diamond.svg'
export { default as IconClockCountdown } from '@/assets/icons/clockcountdown.svg'
export { default as IconHandSwipeRightYellow } from '@/assets/icons/handswiperight-yellow.svg'
export { default as IconPlugChargingRed } from '@/assets/icons/plugcharging-red.svg'
export { default as IconPlugsYellow } from '@/assets/icons/plugs-yellow.svg'
export { default as IconRepeatGreen } from '@/assets/icons/repeat-green.svg'
